# Generated by Django 5.2.8 on 2025-11-22 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museus', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('tema', models.CharField(max_length=100)),
                ('museu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='museus.museu')),
                ('obras', models.ManyToManyField(blank=True, related_name='eventos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
