# Generated by Django 5.2.8 on 2025-11-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('horario_funcionamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Museu',
                'verbose_name_plural': 'Museus',
            },
        ),
    ]
