# Generated by Django 5.2.8 on 2025-11-22 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
        ('galerias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('localizacao', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='artistas.artista')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='galerias.galeria')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
