# Generated by Django 5.2.8 on 2025-11-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('galerias', '0001_initial'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('eventos', models.ManyToManyField(blank=True, related_name='catalogos', to='eventos.evento')),
                ('galerias', models.ManyToManyField(blank=True, related_name='catalogos', to='galerias.galeria')),
                ('obras', models.ManyToManyField(blank=True, related_name='catalogos', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
            },
        ),
    ]
